catalog
catalogDescription
	^ 'This project is an implementation of a FAMIX model difference algorithm based on Similarity Flooding algorithm as defined by Sergey Melnik, Hector Garcia-Molina, and Erhard Rahm in ''Similarity flooding: A versatile graph matching algorithm and its application to schema matching'' and in the technical report associated.
Check the github repository for documentation [https://github.com/juliendelplanque/SFDiff].'