SystemOrganization addCategory: #'SimilarityFlooding-Diff'!
SystemOrganization addCategory: 'SimilarityFlooding-Diff-CandidatesChooser'!
SystemOrganization addCategory: 'SimilarityFlooding-Diff-Diffs'!
SystemOrganization addCategory: 'SimilarityFlooding-Diff-Finder'!
SystemOrganization addCategory: 'SimilarityFlooding-Diff-GraphBuilders'!
SystemOrganization addCategory: 'SimilarityFlooding-Diff-Traits'!
