SystemOrganization addCategory: #'SimilarityFlooding-DiffOrion'!
SystemOrganization addCategory: 'SimilarityFlooding-DiffOrion-CandidatesChooser'!
SystemOrganization addCategory: 'SimilarityFlooding-DiffOrion-Diffs'!
SystemOrganization addCategory: 'SimilarityFlooding-DiffOrion-Finder'!
SystemOrganization addCategory: 'SimilarityFlooding-DiffOrion-GraphBuilders'!
SystemOrganization addCategory: 'SimilarityFlooding-DiffOrion-Traits'!
